# MAPPO parameters

# Detailed explanation for each hyper parameter can be found in ray/rllib/agents/ppo/ppo.py


algo_args:
  use_gae: True
  lambda: 0.99
  kl_coeff: 0.2
  batch_episode: 5
  num_sgd_iter: 10
  vf_loss_coeff: 1.0
  lr: 0.0005
  entropy_coeff: 0.02
  clip_param: 0.3
  vf_clip_param: 10.0
  batch_mode: "truncate_episodes"

  lr_schedule:
  - - 0
    - 0.0005
  - - 100000
    - 0.0001
  - - 500000
    - 0.00005
  - - 1000000
    - 0.00001
  - - 10000000
    - 0.0000001

  entropy_coeff_schedule:
  - - 0
    - 0.02
  - - 2000000
    - 0.01
  - - 4000000
    - 0.005
  - - 6000000
    - 0.001
  - - 8000000
    - 0.000001